### ISSUE TITLE
[User Story] Adding orders manually and delivery calculation based on it

### ISSUE THREAD

**Issue by belosh59** [GoodsPartner/GoodsPartner#1036]
Story flow description
1. "Orders" tabs has button "Create"

2. User click button and modal for opens with request to fill the necessary order-related fields
2.1 User could choose address from cache

3. User click "Save" button on form when order information populated, as the result Order saved

4. [Nice todo] Order should have modification option to modify specified information in case of mistake

5. User create delivery and respective orders being created for that date

**Comment by 0ffffh** [comment]
Maybe one of the way is add some like 'custom' column to the table orders with true/false flage, for modifying/deleting/updating only custom added orders

**Comment by belosh59** [comment]
We have resolved it with Tasks
