### ISSUE TITLE
Tasks upload (xlsx)

### ISSUE THREAD

**Issue by GuchiTheHasky** [GoodsPartner/GoodsPartner#1096]
- Create a template with columns,
required: 
(Дата, Клієнт, Доставка 'кг');
optional: 
(Адреса, Забрати 'кг', Доставка можлива з... , Доставка можлива до... , Потребує заморозки, Доступність доїзду, Час розгрузки, Опис завдання);

- Add the ability to upload a file(xlsx);

- Parsing of the uploaded file;

- Add the ability to dawnload a template;

- Create a task list based on the received information or default information;

**Comment by belosh59** [comment]
dawnload -> download :) 
```
Create a task list based on the received information or default information;
```
Yes and it could happen that address specified in file is not matching the ClientAddresses cache, then we need to allow for address resolution as we do for regular orders
