### ISSUE TITLE
[Arianta] [Investigation/Design] Require logic to differentiate Center from Region

### ISSUE THREAD

**Issue by belosh59** [GoodsPartner/GoodsPartner#1170]
We have cars type - minivan / van / truck which has different boundaries in terms of access.

But Arianta has a lot of Minivans and want to have ability to restric some minivans from center but only send them to region

double check arianta map boundaries maybe we just need to make them smaller, bu tstil lwe need to somehow have other cars which are moving outside of the center.

Maybe we could add the different label or tag so that we could trat minivan still diferently 

It also was requested to specify the Ploscha Rynok for only two cars.

[FE]
It seems that we would need to have also mao with square in CFG to confirm and represent to Arianta which boundaries for what was set, maybe several maps - Center, City, Region

Its also sounds more abstract and reasonably to me, then to have Minivan, Van, Truck configuration i ngeneral

**Comment by Rooman** [comment]
fixed
