### ISSUE TITLE
Variable to enable/disable integration functionality

### ISSUE THREAD

**Issue by belosh59** [GoodsPartner/GoodsPartner#1240]
This should help us to use one common main branch for different kind of clients 

We need a property in appplication.yml which switch the behaviour from GrandeDolche kind of where we integrating with 1C once the delivery created, to a Arianta kind of when we work only with Tasks and delivery should be ready for calculation once the Tasks fetched

That would help us to merge both branches and do not deal with separate development fro diffrent kind of customers anymore

**Comment by persyak** [comment]
I'll write analysis details here, as it becomes quite complex task.

When we use TASKS AND ORDERS mode:
1. when we do resyncOrders, we should not touch tasks. Tasks should have their own flow (like reload tasks that we actually have). So we should be able resync orders and reload tasks independently.

General problem with tasks flow and tasks in general:
1. We should probably segregate loaded from file tasks and manually created tasks. I assume, when we reload tasks from file, we should not delete tasks, that are created manually, as we will have to create them manually again.
