### ISSUE TITLE
Setup full Ukraine OSM map

### ISSUE THREAD

**Issue by belosh59** [GoodsPartner/GoodsPartner#1244]
We need to do the following:
1.  Set in the configuration Full Ukraine map here :https://download.openstreetmap.fr/extracts/europe/
`ukraine-latest.osm.pbf | 2023-10-21 00:58 | 826M |  `

2. Change the general boundaries to cover full Ukraine map

3. Start application and record start up time of the up. The point is that we have map preprocessing and city density calculation once we start app and we need to knwo how much it would take for us for full country like Ukraine.

4. Setup test Delivery from Kyiv to Chernihiv and back and check if that would work

**Comment by SashkoStahovskyi** [comment]
Result:

- Period of osm map process and graph construction  --> 15 min


![Image](https://github.com/GoodsPartner/GoodsPartner/assets/87065959/d657faa4-0917-4383-88a7-29f5540983c0)
![Image](https://github.com/GoodsPartner/GoodsPartner/assets/87065959/59344cc1-c3ee-4394-a1ac-79b03693d893)
![Image](https://github.com/GoodsPartner/GoodsPartner/assets/87065959/0d2c66e6-7a34-41e4-9594-0638d5a94f49)
![Image](https://github.com/GoodsPartner/GoodsPartner/assets/87065959/0009bb95-2afb-4b81-9ff1-4c64bb367806)
![Image](https://github.com/GoodsPartner/GoodsPartner/assets/87065959/2542169e-9261-4d02-b3fa-2d1b9344dc1a)
