### ISSUE TITLE
[Ideation] [Design]  Short-sticky and Expandable left menu section with chosen section highlight

### ISSUE THREAD

**Issue by belosh59** [GoodsPartner/GoodsPartner#1284]
For review and discussion with Arte @Rooman 

Users should invoke left menu and after each click we hide it fro screen clarity.
What if for usability we will fix it to icons only which are highlighted with our blue background in case if specific section chosen. This could be quite useful for our users, less annoying and less moving parts in our beautiful design.

Also I see this pattern being repeated in most of ours significant competitors

<img width="1775" alt="Screenshot 2023-12-30 at 15 13 13" src="https://github.com/GoodsPartner/GoodsPartner/assets/26186899/15020eff-4059-4244-a0b0-bf5031d4dba1">

**Comment by Rooman** [comment]
Do you want something like this? 
https://mui.com/material-ui/react-drawer/#mini-variant-drawer

**Comment by belosh59** [comment]
Oh yeah, looks amazing
