### ISSUE TITLE
Route recalculation

### ISSUE THREAD

**Issue by BogdanParashchak** [GoodsPartner/GoodsPartner#203]
Пересчет маршрутов

актуалізація часу прибуття згідно трафіку на маршруту при кожному завершенні точки на маршруті. (good to have)
в случае неуспевания по TimeWindow? чи дозволяти нам перерахунок маршруту і порядок точок із фрахуванням трафіку. (TODO: need clarification)
Мануальна зміна порядку точок в маршруті в процессі доставки
Якщо программа буде сама пересортовувати

Recalculate Route by accepting updated collection of RoutePoints

**Comment by belosh59** [comment]
Moved to initiatives
