### ISSUE TITLE
[Product] Transparency in terms of the orders to Deliver

### ISSUE THREAD

**Issue by belosh59** [GoodsPartner/GoodsPartner#456]
So far it is not clear how much order and specifically - which orders are going to go in Delivery by GrandeDolce

For example:
We retrieved from 1C - 136 Orders.  Some of them was authoresolved with another DeliveryType, some of them was excluded by intention. In the end we are calculating Delivery for 68 Orders - and this information is available only in logs
We don't have information about that before clicking the calculate button.

So in the end we are getting 4 Routes with 18/22/20/8 Orders which is obviously less then 136 initially retrieved and represented on Orders tab.

**Proposal:**
1)
We could have the following tabs:
- Гранде-Дольче
- Інше
- Вилучені
- Потребують уточнення
- Не розраховані (dynamic)

2)
We could use filtering by DeliveryType and somewhere highlight the count of orders by specified type
Question: But it is not clear to me how to filter by excluded=false

3) 
We could specify count of orders in calculation message:
```
DELIVERY_READY("Доставка готова до калькуляції для ${orderCount} замовлень")
```
It is most easy way to confirm the amount. But it si not easy to review them all e.g. to see specifically which orders included. We would still need filtering feature

**Comment by hubarievanatali** [comment]
The classifier may be the presence or absence of documents.
It would be convenient to view those orders that were not calculated by the model.
