### ISSUE TITLE
[FE] Failed delivery state in case if OrderFetching failed

### ISSUE THREAD

**Issue by belosh59** [GoodsPartner/GoodsPartner#527]
We need some information to highlight that delivery has been failed.
So that user could:
 - recreate delivery
 - have some button to refetch orders

<img width="1426" alt="Screenshot 2023-01-31 at 00 47 20" src="https://user-images.githubusercontent.com/26186899/215629984-71d06921-d2c3-432f-9c99-15f161b06c62.png">

**Comment by Rooman** [comment]
Done and delivered
