### ISSUE TITLE
[BE] Dropped orders remain present when delivery recalculated

### ISSUE THREAD

**Issue by belosh59** [GoodsPartner/GoodsPartner#569]
AR:
- Delivery calculation results in droppedOrders
- Add more cars
- Delivery recalculation - all orders recalculated without dropped route points
- On FE droppedPoints tabs still remain - it looks like there no refresh for Orders tab at all after recalculation 

ER:
- Refresh for OrderTab should happen and we should represent valid lates state

**Comment by Rooman** [comment]
@belosh59 Is it still a valid issue?

**Comment by belosh59** [comment]
Resolved
