### ISSUE TITLE
Blank pages in NP (Nova post) documents

### ISSUE THREAD

**Issue by hubarievanatali** [GoodsPartner/GoodsPartner#591]

**Comment by hubarievanatali** [comment]
Steps to reproduce:
1. Autorization as admin user.
2. Сreate delivery for 08/03/2023, 10/03/2023, approve it.
3. Open a tab Пошта.
4. Click the button "Документи".
5. Open downloaded pdf file.

Expected result:
Each document starts with a new page without blank pages.

Actual result:
Blank pages in the pdf file.

**Comment by hubarievanatali** [comment]
![image](https://user-images.githubusercontent.com/111442362/229275871-653ca4b1-c1cd-4ce5-91ef-99ef5c4fa9f6.png)

**Comment by hubarievanatali** [comment]
![image](https://user-images.githubusercontent.com/111442362/229275900-4f532e29-5495-497f-80aa-f753ad5a2f49.png)

**Comment by SerhiiTrehubenko** [comment]
Документ по сути не содержит пустых страниц, "пустая страница" - это отсканированная (пустая страница) оригинала сертификата качества, т.е. исходный quality document уже содержал такого рода контент. P.S. если посмотреть в верхний  правый угол этой пустой страницы то можно увидеть след от скрепки!)
