### ISSUE TITLE
Missing the saved task in task list

### ISSUE THREAD

**Issue by hubarievanatali** [GoodsPartner/GoodsPartner#592]
Steps to reproduce:

Autorization as admin user.
Go to Завдання at side menu.
Click the button "Додати задачу".
Fill input fields at opened dialogue window  "Додати задачу" and click the button Зберегти.

Expected result:
Appearance of this task in the task list. 
Tab Завдання is presented at the page Доставка on current date.

Actual result:
Missing the saved task in task list. 
Missing the tab Завдання at the page Доставка on current date.

**Comment by hubarievanatali** [comment]
![image](https://user-images.githubusercontent.com/111442362/229276900-0c809079-b02a-44ad-bd34-cb97b7020a58.png)

**Comment by hubarievanatali** [comment]
![image](https://user-images.githubusercontent.com/111442362/229276927-2bbd63d2-dcaf-4b08-b651-09e2ef251a96.png)

**Comment by belosh59** [comment]
Unable to reproduce neither on local env or PROD.
Could you please doublecheck from you side?
<img width="1774" alt="Screenshot 2023-04-01 at 22 18 44" src="https://user-images.githubusercontent.com/26186899/229314311-1c0f864a-5cf3-4c36-9124-2a8dad2356b4.png">

Here is mine successfully crated task:
http://goods-partner.online/tasks

**Comment by hubarievanatali** [comment]
Yes, today I also could save it

**Comment by hubarievanatali** [comment]
![image](https://user-images.githubusercontent.com/111442362/229374687-31e9d032-17de-4a63-9869-d0f2737bb273.png)

**Comment by belosh59** [comment]
thanks for confirmation
