### ISSUE TITLE
File cannot be uploaded at the dialogue window "Додати задачу"

### ISSUE THREAD

**Issue by hubarievanatali** [GoodsPartner/GoodsPartner#593]
Steps to reproduce:

Autorization as admin user.
Go to Завдання at side menu.
Click the button "Додати задачу".
Fill input fields at opened dialogue window "Додати задачу" and click the button Завантажити документ.
Choose the file at opened dialogue window.

Expected result:
File is uploaded.

Actual result:
File is not uploaded.

**Comment by hubarievanatali** [comment]
![image](https://user-images.githubusercontent.com/111442362/229277913-f51cfce7-1457-4ee9-8619-6315a9a783b8.png)

**Comment by hubarievanatali** [comment]
![image](https://user-images.githubusercontent.com/111442362/229277935-336645ee-4cb1-4344-b2b0-53e5e57990bb.png)

**Comment by hubarievanatali** [comment]
Тепер кнопка не клікабельна взагалі

**Comment by hubarievanatali** [comment]
![image](https://user-images.githubusercontent.com/111442362/229374150-4d9c03a9-b429-49c8-96ce-87921ae76cbc.png)

**Comment by hubarievanatali** [comment]
Now I can’t click the button

**Comment by hubarievanatali** [comment]
![image](https://user-images.githubusercontent.com/111442362/229374270-c9d3a1f0-624d-4a49-abce-881f7db361d0.png)

**Comment by Rooman** [comment]
Fixed
