### ISSUE TITLE
Fix document name for car loading

### ISSUE THREAD

**Issue by belosh59** [GoodsPartner/GoodsPartner#701]
[%5B2023-05-01_15-18-30%5D%D0%97%D0%B0%D0%B2%D0%B0%D0%BD%D1%82%D0%B0%D0%B6%D0%B5%D0%BD%D0%BD%D1%8F_%D0%BC%D0%B0%D1%88%D0%B8%D0%BD_%D0%BD%D0%B0_2023-04-28.xlsx](https://github.com/GoodsPartner/GoodsPartner/files/11368399/5B2023-05-01_15-18-30.5D.D0.97.D0.B0.D0.B2.D0.B0.D0.BD.D1.82.D0.B0.D0.B6.D0.B5.D0.BD.D0.BD.D1.8F_.D0.BC.D0.B0.D1.88.D0.B8.D0.BD_.D0.BD.D0.B0_2023-04-28.xlsx)

<img width="1323" alt="Screenshot 2023-05-01 at 23 14 13" src="https://user-images.githubusercontent.com/26186899/235540932-53706293-80df-4c01-aede-697a8da288e0.png">

Same issue is with documents by route

**Comment by belosh59** [comment]
[2023-04-03_%D0%9C%D0%B5%D1%80%D1%81%D0%B5%D0%B4%D0%B5%D1%81-%D0%92%D1%96%D1%82%D0%BE-Mersedes-Vito_%D0%90%D0%861649%D0%95%D0%A0.pdf](https://github.com/GoodsPartner/GoodsPartner/files/11368535/2023-04-03_.D0.9C.D0.B5.D1.80.D1.81.D0.B5.D0.B4.D0.B5.D1.81-.D0.92.D1.96.D1.82.D0.BE-Mersedes-Vito_.D0.90.D0.861649.D0.95.D0.A0.pdf)
Issue with document by route

**Comment by belosh59** [comment]
Content-Disposition: attachment; filename*=UTF-8''2023-04-03_%D0%9C%D0%B5%D1%80%D1%81%D0%B5%D0%B4%D0%B5%D1%81-%D0%92%D1%96%D1%82%D0%BE-Mersedes-Vito_%D0%90%D0%861649%D0%95%D0%A0.pdf

**Comment by TarasOrlovskyi** [comment]
https://ru.stackoverflow.com/questions/1010188/%D0%9A%D0%B0%D0%BA-%D0%BE%D1%82%D0%BE%D0%B1%D1%80%D0%B0%D0%B7%D0%B8%D1%82%D1%8C-%D0%BA%D0%B8%D1%80%D0%B8%D0%BB%D0%BB%D0%B8%D1%86%D1%83-%D0%B2-%D0%BD%D0%B0%D0%B7%D0%B2%D0%B0%D0%BD%D0%B8%D0%B8-%D1%84%D0%B0%D0%B9%D0%BB%D0%B0

https://vova-sukhov.livejournal.com/1488.html

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition
