### ISSUE TITLE
INPROGRESS RoutPoint status gone

### ISSUE THREAD

**Issue by TarasOrlovskyi** [GoodsPartner/GoodsPartner#715]
Review:
Grande Dolce set status SKIPPED for many RoutePoints manually. After that they noticed that none of the RoutePoints had the INPROGRESS status. So they were blocked on this Route and Driver can't continue his Route.

Need:
1. Investigate and reproduce in witch case INPROGRESS RoutePoint status can disappeared on route.
2. Fix it

**Comment by belosh59** [comment]
Not reproducible anymore
