### ISSUE TITLE
Fixed Documents by Route

### ISSUE THREAD

**Issue by TarasOrlovskyi** [GoodsPartner/GoodsPartner#716]
Need to save Documents for Driver on server file system when logistician approves route. When we need the documents app should get file from file system instead of get data from db and create new dynamic file.

Think about 
- clearing file system (sheduller etc). 
- If file will be removed and we will need old documents how can we get them?
- if we add some tasks that day after route approving, how will these tasks be recorded in the route sheet for the DRIVER?
- do we even need to do this?

**Comment by belosh59** [comment]
Not needed anymore
