### ISSUE TITLE
[WebApp] There is no Task menu for Driver

### ISSUE THREAD

**Issue by belosh59** [GoodsPartner/GoodsPartner#718]
1. Login under driver
2. Tasks should be represented

**Comment by Rooman** [comment]
Maybe we shouldn't support driver functionality on web version, and even forbid them to login in web:) Give link to mobile app instead :)

**Comment by belosh59** [comment]
Its a minor staff but I sure driver could for example like to review his full route at monitor at home for example

**Comment by belosh59** [comment]
By the way not sure if we show the full route on mobile app

**Comment by belosh59** [comment]
We decide to postpone support for FE version for drivers only mobile app at the moment
