### ISSUE TITLE
Cannot invoke "java.util.List.stream()" because "authorities" is null

### ISSUE THREAD

**Issue by GoodsPartner** [GoodsPartner/GoodsPartner#727]
Strange backend log when loading application after restart (maybe it's related not to restart, but to token  expiration)

![image](https://github.com/GoodsPartner/GoodsPartner/assets/116003721/49fc4c37-959b-4fd1-859c-f424033ed6aa)

**Comment by belosh59** [comment]
Its related to the attempts to set up  live-stream after restart with open Browser window

In any case we are moving to Websockets - this is not relevant anymore
