### ISSUE TITLE
[FE] First login always hung 

### ISSUE THREAD

**Issue by belosh59** [GoodsPartner/GoodsPartner#731]
<img width="1788" alt="Screenshot 2023-05-10 at 07 55 21" src="https://github.com/GoodsPartner/GoodsPartner/assets/26186899/84fb1676-66be-478e-891c-4896ff109688">

Console:
<img width="1791" alt="Screenshot 2023-05-10 at 08 02 45" src="https://github.com/GoodsPartner/GoodsPartner/assets/26186899/1bf31067-5ba2-492f-8498-fc66c7d3d40d">

**Comment by Rooman** [comment]
Cannot reproduce

**Comment by belosh59** [comment]
Reproduced just now


![Image](https://github.com/GoodsPartner/GoodsPartner/assets/26186899/a14d95c4-903b-4f8c-9856-2cdf2de12dec)

**Comment by belosh59** [comment]
Unable to reproduce on DEV or PROD, probably local issue
