### ISSUE TITLE
Сan't add a new user

### ISSUE THREAD

**Issue by GuchiTheHasky** [GoodsPartner/GoodsPartner#745]
Tried to add a new user (driver or logistician), but they are not being added and no errors are occurring.

**Comment by belosh59** [comment]
Dev env correct?

**Comment by belosh59** [comment]
<img width="1789" alt="Screenshot 2023-05-16 at 00 37 53" src="https://github.com/GoodsPartner/GoodsPartner/assets/26186899/e87fc085-2fe7-4612-9076-2d5829270702">

```
JSON parse error: Unrecognized field "driverLicence" (class com.goodspartner.dto.UserDto), not marked as ignorable; nested exception is com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "driverLicence" (class com.goodspartner.dto.UserDto), not marked as ignorable (7 known properties: "enabled", "userName", "login", "id", "email", "role", "driverLicense"]) at [Source: (org.springframework.util.StreamUtils$NonClosingInputStream); line: 1, column: 95] (through reference chain: com.goodspartner.dto.UserDto["driverLicence"])
```

<img width="598" alt="Screenshot 2023-05-16 at 00 38 24" src="https://github.com/GoodsPartner/GoodsPartner/assets/26186899/5224558c-a641-411b-a8a8-d7141fcdd4df">
