### ISSUE TITLE
Can't add a new car

### ISSUE THREAD

**Issue by GuchiTheHasky** [GoodsPartner/GoodsPartner#746]
Tried to add a new vehicle, but it is not being added and no errors are occurring.

**Comment by belosh59** [comment]
@GuchiTheHasky 
Unable to reproduce on DEV:
<img width="1763" alt="Screenshot 2023-05-16 at 00 10 16" src="https://github.com/GoodsPartner/GoodsPartner/assets/26186899/dc048542-b527-49f3-b3c6-a76cae5a3cec">
