### ISSUE TITLE
Error during uploading orders

### ISSUE THREAD

**Issue by GuchiTheHasky** [GoodsPartner/GoodsPartner#747]
Tried to create a new delivery on 20.02.23, saw:

- Administrator Maxym created the delivery;
- Synchronization of orders with 1C started;
- Error occurred while uploading orders from 1C;

When trying to create a delivery on the same date again:
- Delivery on date: "Date" already exists, choose a different date.

**Comment by belosh59** [comment]
I cannot reproduce this.
We could have a demo on this.

I have different timezone thats why
<img width="1275" alt="Screenshot 2023-05-16 at 00 50 47" src="https://github.com/GoodsPartner/GoodsPartner/assets/26186899/5e51200c-b42a-4531-9e5b-39cd35a2e65d">
 it show 19.02 but I was specifying 20.02
