### ISSUE TITLE
Инвестигейт - Показывает ордера с флагом (обговоренным) и отдельно без флага.

### ISSUE THREAD

**Issue by BogdanParashchak** [GoodsPartner/GoodsPartner#75]

**Comment by BogdanParashchak** [comment]
Чтобы человек видел что у него есть несогласованные на отгрузку ордера по которым мы сейчас будем строить маршрут

**Comment by BogdanParashchak** [comment]
Наразі програма вивантажує з 1С замовлення (ордери) на певну дату. Для цих замовлень в 1С мають бути виписані накладні + ордери мають бути проведені. Уточнити у клієнта, що саме має потрапити в маршрут.

**Comment by hubarievanatali** [comment]
1.	 Логіст відкриває сторінку «Доставка» , натискає кнопку «Сформувати нову доставку», на екрані з'являється діалогове вікно, де йому пропонується обрати дату, на яку будуть сформовані доставки. 
2.	 Логіст обирає потрібну дату та натискає кнопку «Сформувати доставку».
3.	Логіст потрапляє на сторінку «Доставка» на конкретну обрану дату, у табі «Замовлення» бачить перелік замовлень на обрану дату у вигляді таблиці. Замовлення можуть мати сформовані видаткові накладні, у випадку їх відсутності має відображатися флаг.
4.	Логіст може сформувати маршрут, розрахувати завантаження, але перевести Доставку у статус «В роботі?» логіст може лише коли у всіх замовлень на конкретну дату сформовані видаткові накладні. 

Sub-variations
4а. Якщо логіст хоче перевести «Доставку» на конкретну дату у статус «У роботі?», але дана Доставка містить у собі замовлення без флага, то на екрані з'являється спливаюча підказка: «Дана доставка містить замовлення без сформованих накладних».
