### ISSUE TITLE
manual route for specific car

### ISSUE THREAD

**Issue by TarasOrlovskyi** [GoodsPartner/GoodsPartner#896]
add a manual mode option for the car. Now it is possible to turn the car on and off for automatic route calculation. But you need to be able to turn on and off the manual mode for the car when the automatic route calculation for car is turned off. That is, if manual mode is enabled, you can set a task for this car for this day, and then this car will not be taken into account in the automatic route calculation mode, and the route will be built exclusively for additional tasks

**Comment by belosh59** [comment]
Moved to initiatives
